spring:
  datasource:
    username: root
    password: Sainithin@2002
    url: jdbc:mysql://localhost:3306/microArch?createDatabaseIfNotExists=true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
 port: 8081

# Application messages goes here
auth-service:
 messages: 
  userReg: User Created
  userRegErr: User Creation Failed
  login: Login Success
  loginErr: Invalid Credentials  
